### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by travisbusen** [chriskol/Google-Docs-Desktop-OSX#1]
This is amazing, thank you for creating this!  On macOS 10.12.3 I am getting a browser not supported warning.

**Comment by chriskol** [comment]
I'm still on 10.11 and am keeping Siri off my computer as long as possible.  Not sure what would be causing this though.  Is it still an issue?

**Comment by mint5auce** [comment]
Still an issue in 10.13.1. 

What is the underlying browser engine?

**Comment by chriskol** [comment]
It's working fine on my end with 10.13.  Not sure if that's the same as 10.13.1 but I don't appear to have that update available.  MacGap uses WebViews I believe.  Do you not have xcode installed by chance?  Are you building from source or downloading a binary release?

**Comment by jayjlawrence** [comment]
I had a look at the user agent headers for my current Safari and then for the MacGap app. There is a version difference on my system. I am not sure how the version of AppleWebK is selected...

OS 10.11.6 (security update 2018-001 not installed yet)

Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6
MacGap App: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) MacGap

What doesn't make much sense to me is that I dragged the MacGap app over to a Mac running 10.12.3 and it is reporting AppleWebKit/602..4.8

What did make me happy is "Dragged the MacGap app over to another Mac" and it "Just worked". Ahhh :)

**Comment by chriskol** [comment]
Haha.  Well that's good to hear that it worked.  It's bizarre that error was happening as I never experienced on whichever version I was running.  I'm thinking it's more of a [MacGap](https://github.com/MacGapProject/MacGap2) issue though.

**Comment by chriskol** [comment]
Actually, another possibility might be that you downloaded a binary that I built on my system from releases instead of building yourself.  This means that when the app is built, it's built perhaps using the resources on my system and is, as a result, creating a mismatch or error on your own system?

Can you try building from source and see if you still get the same issues?  Maybe there needs to be a release for like every version of OSX?  Or maybe I should just stop with the releases so as not to cause further confusion? Or only support the latest version of OSX for binaries?

**Comment by jorisw** [comment]
FWIW I did not have this problem, other than Google Docs saying "Please use a supported browser" which I could simply dismiss.

Running macOS 10.13.6 on a 2016 MBP.

My guess is that they check the _browser_ in the User Agent, not the WebKit version. So they're looking for a stock Safari, Chrome, Firefox or IE to run on.

**Comment by chriskol** [comment]
It would be helpful to know if this was compiled from source or the binary was used.  I wouldn't be surprised if the binary I compiled and put in releases doesn't cause wonky things to happen for people using different versions of macOS/xcode/etc. than I had at the time of building.

**Comment by jorisw** [comment]
In my case, the binary.

**Comment by chriskol** [comment]
I'd try building the app from source and seeing if you still get the issue.
