### ISSUE TITLE
Provide app for v2.0

### ISSUE THREAD

**Issue by MiMoHo** [chriskol/Google-Docs-Desktop-OSX#4]
Could you provide a compiled app for v2.0 on OS X as well?

**Comment by chriskol** [comment]
I'd recommend against using the binary releases at this point.  There have been issues with people downloading them and using them on different versions of OSX from what I've compiled them on and it causing problems.

That is, me compiling on whatever version of OSX I'm running can cause problems for you if you aren't running on the same version.  As I'm not sure what the future holds in terms of me or users of the app being up to date on the latest OSX, I'm just going to stop making releases for the foreseeable future and avoid issues.

Building from source following the directions in the instructions is the definite recommended method.
