### ISSUE TITLE
Automatic in-app updates

### ISSUE THREAD

**Issue by MiMoHo** [chriskol/Google-Docs-Desktop-OSX#5]
Could the application automatically check for updates and ask to download and install them?

**Comment by chriskol** [comment]
The nature of this app is that it's just a wrapper.  I wouldn't expect any substantial updates at this point unless it's superficial things like icon updates etc. 

Further to this, I'd recommend against using the binary releases.  There have been issues with people downloading them and using them on different versions of OSX from what I've compiled them on and it causing problems.  

Building from source is the definite recommended method.
